# Generated by Django 4.2.2 on 2023-06-28 20:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_subtask_rename_todo_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.task'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
