# Generated by Django 4.2.2 on 2023-06-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_category_task_categ'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtask',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
